AllCops:
  Exclude:
    - '*.gemspec'
    - 'spec/*.rb'
    - '**/generated_parser/*'

inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Description: Limit lines to 80 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#80-character-limits
  Enabled: true
  Max: 130

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Enabled: false
  Max: 400

Metrics/AbcSize:
  Enabled: false
  Max: 50

Metrics/MethodLength:
  Enabled: false
  Max: 50

Style/BlockComments:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

# Configuration parameters: AllowForAlignment.
Style/ExtraSpacing:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  Enabled: false

# Offense count: 1
Metrics/CyclomaticComplexity:
  Enabled: false
  Max: 11

# Offense count: 1
Metrics/PerceivedComplexity:
  Enabled: false
  Max: 14

# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: false
